# *** This Dockefile is generated by KloverCloud *** #
FROM container-registry.console.klovercloud.com/klovercloud/golang:1.14 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/bin/go .

FROM container-registry.console.klovercloud.com/klovercloud/golang:1.14

RUN useradd -ms /bin/bash klovercloud

WORKDIR /home/klovercloud

COPY --from=builder /app/bin .


EXPOSE 8080

USER klovercloud
CMD ["./go"]